# Generated by Django 5.2.7 on 2025-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='available_date',
        ),
        migrations.RemoveField(
            model_name='house',
            name='status',
        ),
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='house',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='landlord_name',
            field=models.CharField(default='Landlord', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='house',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
