# Generated by Django 5.2.7 on 2025-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_remove_house_available_date_remove_house_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='landlord_name',
            field=models.CharField(default='Landlord', max_length=100),
        ),
    ]
