# Generated by Django 5.2.7 on 2025-11-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
