# Generated by Django 5.2.7 on 2025-11-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_subscription_payment_houseaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='house',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='tenant',
        ),
        migrations.AddField(
            model_name='house',
            name='pending_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='HouseAccess',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
