# Generated by Django 5.2.7 on 2025-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_remove_payment_house_remove_payment_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='landlord_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='house',
            name='landlord_uid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
