# Generated by Django 5.2.7 on 2025-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_alter_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
