# Generated by Django 4.2.11 on 2025-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_house_landlord_email_house_landlord_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.JSONField(default=list),
        ),
    ]
