# Generated by Django 5.2.7 on 2025-11-26 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_add_house_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Reason why this message was flagged'),
        ),
        migrations.AddField(
            model_name='message',
            name='flagged_at',
            field=models.DateTimeField(blank=True, help_text='When this message was flagged', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='flagged_by',
            field=models.ForeignKey(blank=True, help_text='Admin who flagged this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Whether this message has been flagged for moderation'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Whether this message is detected as spam'),
        ),
    ]
