# Generated by Django 4.2.11 on 2025-11-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_house_latitude_house_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='house',
            name='longitude',
        ),
    ]
